In [1]:
def relu(x):
    return np.maximum(0, x)

In [2]:
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)



[1 2 3 4]


In [3]:
np.ndim(A)


1

In [4]:
A.shape[0]

4

In [5]:
B = np.array([[1,2], [3,4], [5,6]])

In [6]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
np.ndim(B)

2

In [8]:
B.shape

(3, 2)

In [9]:
A = np.array([[1,2], [3,4]])
A.shape

(2, 2)

In [10]:
B = np.array([[5,6], [7,8]])
B.shape

(2, 2)

In [11]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [12]:
A = np.array([[1,2,3], [4,5,6]])
A.shape

(2, 3)

In [13]:
B = np.array([[1,2], [3,4], [5,6]])
B.shape

(3, 2)

In [14]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [15]:
C = np.array([[1,2], [3,4]])
C.shape

(2, 2)

In [16]:
A.shape

(2, 3)

In [17]:
np.dot(A, C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [18]:
A = np.array([[1,2], [3, 4], [5,6]])
A.shape

(3, 2)

In [19]:
B = np.array([7,8])
B.shape

(2,)

In [20]:
np.dot(A, B)

array([23, 53, 83])

In [21]:
X = np.array([1, 2])
X.shape

(2,)

In [22]:
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [23]:
W.shape

(2, 3)

In [24]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
